### PR TITLE
Create task 4

### PR DESCRIPTION
**Pull request by montiiabby**
MOXIE
goswamiabhishek44@gmail.com

### CODE REVIEW

**Comment by gauthamzz** [comment]
its just a circle. not a sunny day.

Hence rejected

**Comment by montiiabby** [comment]
Sir
Sunny day question was incomplete
It just states that do as the previous problem statement.

**Comment by gauthamzz** [comment]
its not a sunny day 😄 . You drew a sun 😄 
Okay no one did it. so hence no points for anyone.

**Comment by montiiabby** [comment]
With due respect sir
I have attempted and worked something
Grace marks ?
😅

**Pull request closed without merging**
